name: my_python_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - et_xmlfile==2.0.0
      - numpy==2.2.2
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pillow==11.1.0
      - psycopg2==2.9.10
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - six==1.17.0
      - ttkbootstrap==1.10.1
      - tzdata==2025.1
